"""Reserved module for language-model integrations used by the application."""

from typing import Protocol
from openai import OpenAI
import os

# ---------- Abstractions ----------


class LLM(Protocol):
    """Contract for language models that generate text from prompts."""

    def generate(self, system_prompt: str, user_prompt: str) -> str:
        """Generate a text response to a prompt.

        Args:
            system_prompt: The system prompt for the model.
            user_prompt: The text to be processed by the model.

        Returns:
            A natural-language response generated by the model.
        """
        ...


# ---------- Implementations ----------


class OpenAILLM:
    """Generate text using the OpenAI API."""

    last_response_id = None

    def __init__(
        self,
        model_name: str = "gpt-4.1-mini",
        max_tokens: int = 500,
    ):
        """Configure the model, temperature, and output limit for generation.

        Args:
            model_name: Model identifier passed to the OpenAI Responses API.
            temperature: Generation temperature retained as configuration; it is
                not currently passed in the API request.
            max_tokens: Maximum output tokens requested from the API.

        Returns:
            None.
        """
        self.model_name = model_name
        self.max_tokens = max_tokens

    def generate(self, system_prompt: str, user_prompt: str) -> str:
        """Generate a text response to a prompt.

        Args:
            system_prompt: The system prompt for the model.
            user_prompt: The text to be processed by the model.

        Returns:
            A natural-language response generated by the model.
        """
        client = OpenAI(
            api_key=os.getenv("AZURE_AD_TOKEN_PROVIDER"),
            base_url=os.getenv("AZURE_FOUNDARY_ENDPOINT"),
        )

        # Get a response
        response = client.responses.create(
            model=self.model_name,
            instructions=system_prompt,
            input=user_prompt,
            stream=False,
            max_output_tokens=self.max_tokens,
            previous_response_id=self.last_response_id,
        )
        self.last_response_id = response.id
        return response.output_text
